[latest]
title = "보안뉴스 ─ 전체기사"
url = "https://www.boannews.com/media/t_list.asp"
entrySelector = "div[id='news_area'] div.news_list"
titleSelector = "span.news_txt"
linkSelector = "a"
waitUntil = "networkidle"
